services:
  - type: web
    name: django-student-management-system
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn school.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: WEB_CONCURRENCY
        value: 2
    healthCheckPath: 